### ISSUE TITLE
Appsettings at compile-time

### ISSUE THREAD

**Issue by boginw** [aau-giraf/web-api#10]
**Is your feature request related to a problem? Please describe.**
In solving [this](https://github.com/aau-giraf/wiki/issues/34) issue, we have noticed that `appsettings` is required at compile-time. This is a very big inconvenience for our servers, as they need to provide secrets inside the docker images. 

**Describe the solution you'd like**
Make `appsettings` not required at compile-time.

**Describe alternatives you've considered**
Alternatively, we need to store secrets in Dockerfiles, which is a big no-no

**Additional context**
For further information please ask @thomaslhansen

**Comment by thomaslhansen** [comment]
This was fixed in PR #13 where the appsettings.json must be passed into each container as a volume, see https://github.com/aau-giraf/giraf-production-swarm/blob/master/docker-compose.yml for more information.
