### ISSUE TITLE
As a guardian I can create a new SuperUser

### ISSUE THREAD

**Issue by joandrsn** [aau-giraf/web-api#104]
**Describe the bug**
If I send the following to the `v1/Account/register` endpoint, I get a successful response

**To Reproduce**
1. Login as a guardian 
2. Post the following to the `​/v1​/Account​/register`-endpoint:
```
{
  "username": "jonas",
  "password": "password",
  "displayName": "jonas",
  "departmentId": 2,
  "role": "SuperUser"
}
```

**Expected behavior**
I expected an error, telling me I'm unauthorized.

**Actual behavior**
I get a successful response. 
I can now login with this superuser and further abuse the API.

**Screenshots**
Request:
![image](https://user-images.githubusercontent.com/5766695/80090919-8f8da200-8560-11ea-9dfb-9e6ec4a164a1.png)
Response:
![image](https://user-images.githubusercontent.com/5766695/80090996-acc27080-8560-11ea-86dd-3cb810851215.png)

The response after logging in as the newly created user and requesting GET `/v1/User`:
![image](https://user-images.githubusercontent.com/5766695/80091092-d24f7a00-8560-11ea-95b6-4de135c12e96.png)

**Comment by Kaliahh** [comment]
What is a "SuperUser"?

**Comment by dkalaxdk** [comment]
SuperUsers are users who should be able to create Guardians, and other SuperUsers. Therefore guardians should not be able to create SuperUsers. This seems related to #105

**Comment by ChrisBuchardt** [comment]
As of now Super users are named as Admins and as of Semester 2021E are not requied for the basis functionality of Giraf / They will be needed at some point but I will close this issue to avoid confusion
