### ISSUE TITLE
As a guardian i can create Citizens in another department.

### ISSUE THREAD

**Issue by DumbLol** [aau-giraf/web-api#105]
**Describe the bug**
Guardians can currently create users in departments they themselves are not in. This seems like a bug.

**To Reproduce**
1. Go to swagger and login as a guardian: i used graatand.

2. Click on the user endpoint /v1/user, you should see something like this: 
![image](https://user-images.githubusercontent.com/17495619/80093776-66bbdb80-8565-11ea-97f1-eb48c1791722.png)

3. Now select the account endpoint `/v1/account/register` and create a user in an existing department that your guardian is not in.
I created this user: 
```
{
  "username": "citizen34",
  "password": "password",
  "displayName": "citizen34",
  "departmentId": 2,
  "role": "Citizen"
}
```
4. I got this response: 
![image](https://user-images.githubusercontent.com/17495619/80093888-9834a700-8565-11ea-9caf-5d88f7873ca7.png)

**Expected behavior**
Guardians should not be able to create citizens in other departments.
In addition, should a guardian do this by mistake they cannot delete the newly created Citizen

**Actual behavior**
I would expect an error to appear, saying the guardian cannot create the citizen in another department.

**Comment by TobiasNielsen** [comment]
Same problem for Departments users

**Comment by Kaliahh** [comment]
What is a "Department"? Is it a different institution (i.e. Birken or Egebakken) or within the same institution?

**Comment by dkalaxdk** [comment]
> What is a "Department"? Is it a different institution (i.e. Birken or Egebakken) or within the same institution?

Yes
