### ISSUE TITLE
Creating a new activity to a weekplans date with a pictogram with blank title will result in an exception

### ISSUE THREAD

**Issue by joandrsn** [aau-giraf/web-api#114]
**Describe the bug**
If you send a new activity containing only a pictogram with an ID, the execution throws an exception informing the user that of a `NOT NULL` constraint failing.
This is because the endpoint tries to create a new Pictogram with a given ID and save it to the database.

**To Reproduce**
Currently this test produces the bug:
https://github.com/aau-giraf/web-api/blob/055d11c9cd593a60c9dc06a0c5c2d1eb4c532db7/GirafIntegrationTest/tests/test_activity_controller.py#L77-L88

**Expected behavior**
Either to handle it - giving a default title. Or telling the user that she did something wrong (Errorcode 400?).

**Actual behavior**
A stacktrace is returned.

**Comment by kbwsoorensen** [comment]
Lukkes på baggrund af pull request.
