### ISSUE TITLE
Images should be hashed, and saved in the ImageHash row 

### ISSUE THREAD

**Issue by dkalaxdk** [aau-giraf/web-api#159]
**Describe the solution you'd like**
Images should be hashed, and stored in the database table.
As this should be used when implementing hashing, as it can be used to compare images.

**Additional context**
This is related to #47 but this neeeds to be implemented instead.

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 159](https://trello.com/c/hRyOeg0R/48-issue-159)
