### ISSUE TITLE
As a developer I would like for pictograms to have a GirafUser indicating the creating user, so that I can make sure that only the creating user can delete pictograms.

### ISSUE THREAD

**Issue by AdrianPlesner** [aau-giraf/web-api#162]
**Is your feature request related to a problem? Please describe.**
This issue is related to aau-giraf/weekplanner#273 and aau-giraf/api_client#74

**Describe the solution you'd like**
The get routes in pictogram controller should add the related GirafUser to the model.

**Additional context**
Any platform

Updated to link properly.

**Comment by Kaliahh** [comment]
Replaced by #165
