### ISSUE TITLE
Searching pictograms should not be case sensitive

### ISSUE THREAD

**Issue by soenderby** [aau-giraf/web-api#167]
**Is your feature request related to a problem? Please describe.**
The issue is that searching pictograms yields different result, depending on whether or not the search query contains capital letters.
This is the same as aau-giraf/weekplanner#622, but the problem lies in the web-api.

**Describe the solution you'd like**
To convert the search query and the pictogram titles, to all lowercase letters when they are compared

**Describe alternatives you've considered**
I considered converting the search query to all lowercase, before sending it to the web-api. But in that case it would be compared to pictogram titles that could contain capital letters, which could yield incorrect results

**Comment by dkalaxdk** [comment]
Solved in #169
