### ISSUE TITLE
Setup CICD pipeline with three different environtments

### ISSUE THREAD

**Issue by TrulyThomas** [aau-giraf/web-api#191]
## Description
**Describe the Task** \
We would like to have a CICD pipeline setup with three different environments setup to assist in the development process.
The environments are:
- Development
- Test
- Production

The CICD pipeline should run the tests in the test environment on every release of the solution.

**Possible Suggested Solution**  
- Edit the appsettings.json file and have the connection string be the connection string for the current environment
- Clean the database for the test and production enviromentes and have the test environment initialized with test data.

**Comment by andreaskrath** [comment]
This issue makes no sense to be frank.

The CI/CD pipeline currently builds the solutions and performs unit and integration tests, which covers the **Test** environment.

Settings up a development environment makes no sense, as this is essentially a local version of the solution, which is what the **Test** environment already does to perform the unit and integration tests.

Lastly, a production environment would require connecting to the production database among other things, which should never be a part of a pipeline.
