### ISSUE TITLE
Implement interfaces for authentication of users

### ISSUE THREAD

**Issue by TrulyThomas** [aau-giraf/web-api#194]
## Description
**Describe the Task** \
When authenticating users in the backend the authentication should use an interface to streamline the authentication process for more user types.

**Possible Suggested Solution**  
- The plan is to create an interface that all user types should implement which has methods such as Authenticate(), which handle the authentication of multiple users without the need for sweeping backend changes every time.

**Comment by JMyrtue** [comment]
After inspection, this issue is deemed irrelevant.

Two months after this issue was created, enum roles were added to the code base, which now seems to handle this functionality.

See #214
