### ISSUE TITLE
Not able to get the role of a user

### ISSUE THREAD

**Issue by JakobFaarGreg** [aau-giraf/web-api#227]
## Description
**Describe the bug** \
When logging in to an account, on the develop branch, there is a rotating loading icon that shouldn't be there.

**To Reproduce**
1. Checkout develop branch.
2. Login to an account
3. Observe spinning loading animation

**Expected behavior** \
No spinning.

**Actual behavior and screenshots** \
The error is as seen in following screenshot.
![loadingerror giraf](https://user-images.githubusercontent.com/56345889/140070356-4d6816ad-9fcc-4fe4-ace8-70b2b50b7386.png)

An error is printed to console as seen in the following screenshot.
![errormessage giraf](https://user-images.githubusercontent.com/56345889/140070147-ae7c8000-4c97-4908-9b78-dd5222c59ca3.png)

**Comment by JMyrtue** [comment]
The error could not be replicated, when run on the develop branch.

It is assumed that the two merges mentioned in the history of this issue, solves it.
