### ISSUE TITLE
QA of authentication and authorization 

### ISSUE THREAD

**Issue by LouiseAJensen** [aau-giraf/web-api#230]
## Description
Check that all endpoints that should be covered by authentication or authorization actually is covered. That entails returning proper responses when authentication fails as well as succesful responses when a user is authenticated and authorized. 

Guide:
https://umayangag.medium.com/jwt-authentication-with-asp-net-core-3-1-identity-for-web-apis-fe36d4bb6630

## Sub Tasks
*Create your own subtask issues on GitHub and link them here in a list.*
- [ ] \<Subtask link>

**Comment by JMyrtue** [comment]
A month after this issue was created, pull request #246 added some authorize functionality.

Since this issue is not strictly formulated in regards to its succession criteria, we expect that the above mentioned pull request completes this issue.
