### ISSUE TITLE
Test WeekTemplateRepository

### ISSUE THREAD

**Issue by TrulyThomas** [aau-giraf/web-api#251]
## Description
We would like to have unit tests ensuring the functionality of the WeekTemplateRepository

**Possible Suggested Solution**  
- Create a file named WeekTemplateRepositoryTest.cs in the GirafRest.Test project
- Create unit tests for the relevant methods in the Repository ( see repository pattern https://tinyurl.com/2p8sadnr)

**Comment by JakobTopholt** [comment]
Hvordan er det her en "Good First Issues" når klassen er tom?
