### ISSUE TITLE
Test ErrorController (error 404)

### ISSUE THREAD

**Issue by ChrisBuchardt** [aau-giraf/web-api#257]
Test of ErrorController has been done for almost all errors, except error 404.

We would like to have the ErrorController tested for the error 404

Suggested area to look into

case StatusCodes.Status404NotFound:
                    return NotFound(new ErrorResponse(ErrorCode.NotFound, "Not found", "You                         
 tried to reach " + Request.Method + ": " + OriginalURL));

Request.Method was not mockable for us

**Comment by Just1Per** [comment]
All tests done except error 404
