### ISSUE TITLE
Authorization integration tests

### ISSUE THREAD

**Issue by manfredhod** [aau-giraf/web-api#281]
## Description
Currently, 7 integration tests are failing in the AuthorizationController.

![Image](https://user-images.githubusercontent.com/74592878/198241368-868d3fd0-c25d-45a4-bc50-e69b82eb207e.png)

**Possible Suggested Solution**  
Find out what makes the integration tests fail and fix the tests.

**Comment by AOsnes** [comment]
The name is misleading but the tests are meaningful
