### ISSUE TITLE
WeekTemplateController integration test DEPRECATED

### ISSUE THREAD

**Issue by manfredhod** [aau-giraf/web-api#286]
## Description
Currently, all the integration tests are failing in the WeekTemplateController.

![Image](https://user-images.githubusercontent.com/74592878/198242548-057a1162-2011-46ea-baa6-6c08f1ba6fd9.png)

**Possible Suggested Solution**  
Find out what makes the integration tests fail and fix the tests.

**Comment by danielalexlarsen** [comment]
can anyone tell me why this is DEPRECATED? 😎
