### ISSUE TITLE
Integrations tests should not run on every commit.

### ISSUE THREAD

**Issue by Just1Per** [aau-giraf/web-api#300]
Integration test (maybe unit test?) should only run in our CI pipeline when making PR to the develop branch and not on every commit. This should be done to save compute time from GitHub Actions.

Potential solutions:
	Go to the file: repo/.github/workflows/*.yml
	Change the “on” command to only run on pull request to the develop branch
	Investigate if test should/how they could run when deploying aswell

**Comment by ltranu20** [comment]
It would not affect nor speed up anything. Accounts can have up to 20 concurrent jobs (40 if pro), meaning the bottleneck is GitHub.

**Comment by andreaskrath** [comment]
This issue a non-issue, branch protection prevents direct commits to development meaning this is no longer a concern.
