### ISSUE TITLE
Version control weekplanner/web-api

### ISSUE THREAD

**Issue by JakobTopholt** [aau-giraf/web-api#301]
Add version check at login between weeplanner/web-api

sometimes people end up using a newer version of the weeplanner on an older version of the web-api or vice-versa.
This has a tendency to create problems and/or issues

**potential solution**
Check the verison of the weekplanner and the web-api and control for a match, when attempting to login. Reject the login if the versison don't match. This should reduce the amount of invalid issues. Profit.

**Comment by JMyrtue** [comment]
This issue is closed as the solution would increase coupling the repositories.

If people experience issues with running the application, it is expected that people logically check and update versions.
