### ISSUE TITLE
Update from .NET 6 to .NET 8

### ISSUE THREAD

**Issue by AOsnes** [aau-giraf/web-api#311]
## Description
**Describe the Task** \
The web-api is currently running on .NET 6. Support for .NET 6 will end in [2024](https://dotnet.microsoft.com/en-us/platform/support/policy). .NET 8 will be released in 2023 which means the GIRAF developers have a year to migrate before support ends. It is recommended to do before last minute.

**Possible Suggested Solution**  
- Download and install the .NET 8 SDK and runtime
- Update the project to run on .NET 8

**Comment by andreaskrath** [comment]
At the time of writing .NET 8 and EF Core 8 are not released yet, the former is scheduled for [November 18th](https://github.com/dotnet/core/blob/main/releases.md#supported-net-versions), with the latter scheduled for a [November release](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew) as well.

However, both .NET and EF Core 8 currently have release candidates, which mean features are stabilized and the only difference between the release candidates and the final releases are bug fixes.

As a result, the decision has been to update both .NET 8 and EF Core 8 from 6 to 8, using the release candidates until the official releases are published.

**Comment by KristianS93** [comment]
Update from .NET 6 to 8 RC is completed, required an update to the AspNetCore.Mvc.Testing package, as integrationtests were failing.

**Comment by andreaskrath** [comment]
Although an update from EF6 to EF Core 8 was mentioned earlier in the issue as part of the upgrade, it will be handled in its own issue.

**Comment by KristianS93** [comment]
Locally working with .NET 8 is fine, however the Github actions cannot build upon .NET 8. This should probably be discussed on the PO meeting.

**Comment by KristianS93** [comment]
Very important: The sdk in the github actions HAS to be changed when the official .NET 8.0 is released.
