### ISSUE TITLE
Architecture update

### ISSUE THREAD

**Issue by KristianS93** [aau-giraf/web-api#326]
## Description
As of now there is 14 different folders inside the Giraf Rest API, by itself this is not a problem, however as the project has grown larger this containing more files and folders, there is a necessity for a thorough update on the overall architecture and the implementation of the architecture. 

The update should also include a new section of testing namely architecture tests, to ensure the expected architecture is correct.

This issue would require 4 things:
- Architectural overhaul (Layers / Projects / Folders).
- Class diagram. 
- Test cases. 
- Documentation update of the architecture. 

**Possible Suggested Solution**  
Solution proposition is to take a look at fitting architecture style, this could potentially be some version of the layered architecture. 
The solution should also have a fitting class diagram, that can be added to the documentation and the wiki of the project, as this would be an enhancement for getting to know the project for future developers. 

Regarding the architecture tests, these tests should ensure, that the communications between layers are withheld, as an example a domain layer containing entities, should not reference the project for the services, however the services project should reference the domain layer. This is possible to test using the NetArchTest nuget package [Nuget](https://www.nuget.org/packages/NetArchTest.Rules/#readme-body-tab) [GitHub](https://github.com/BenMorris/NetArchTest)

Example of how a testcase could be created.
![image](https://github.com/aau-giraf/web-api/assets/82061735/2672b9ee-f1d7-40d5-b109-bdba9e857e3f)

**Definition of Done**
- All endpoints must be tested to ensure the new architecture is functional.
    - This can systematically be accomplished through Swagger.
- All test cases, both unit and integration, must pass under the new architecture.
- The application must be rigorously tested to ensure features are working as before.
    - This can be accomplished with an emulator.

**Comment by andreaskrath** [comment]
It is very likely that [this](https://aau-giraf.github.io/wiki/Development/Web_API/) would also require comprehensive changes, if this part of the wiki should continue to exist at all.

**Comment by KristianS93** [comment]
I have played around with the architecture testing just for fun, and even following examples of:
https://www.ben-morris.com/writing-archunit-style-tests-for-net-and-c-for-self-testing-architectures/
however, I dont seem to be able to make it work, we should take a closer look if we want to do this.

EDIT:
Tried one more time it works in VS but not in Rider 🗡️ 
Correct behavior in my toy project:
![image](https://github.com/aau-giraf/web-api/assets/82061735/68d7eaac-8371-4e72-98be-34dc4808f82f)
Same test and setup in rider:
![image](https://github.com/aau-giraf/web-api/assets/82061735/e8894cd8-d1f9-4473-a5c1-6bf5e12a1af7)
