### ISSUE TITLE
Update wiki installation guide

### ISSUE THREAD

**Issue by andreaskrath** [aau-giraf/web-api#332]
## Description
Some of the recent changes have altered the installation process, and the guide should reflect this.

It would likely also be a good idea to include the process of updating the wiki documentation as part of solving an issue, if it requires this.

**Possible Suggested Solution**  
- Update the wiki with new installation instructions.

## Sub Tasks
- Somehow involve this process as a required part of a pull request being merged.

**Comment by KristianS93** [comment]
https://github.com/aau-giraf/wiki/pull/307
