### ISSUE TITLE
Feature 17 conversion of day enum from api-client

### ISSUE THREAD

**Issue by HaZzM22** [aau-giraf/web-api#37]
**Describe the bug**
PostActivity from feature 17 does not convert Days correctly.

**To Reproduce**
1. Use the web-api PostActivity endpoint through the flutter application.
2. Conversion from flutter applications Weekday enum to web-api Days does not work

**Expected behavior**
Conversion should work correctly. i.e friday goes to friday

**Actual behavior**
Conversion does not work correctly. i.e friday goes to index 0 (nothing)

**Environment (please complete the following information):**
MariaDB web-client
Windows 10
Android emulator pixel_c

**Comment by KVISDAOWNER** [comment]
#17
