### ISSUE TITLE
Integration Tests are not part of the CI in github actions

### ISSUE THREAD

**Issue by KVISDAOWNER** [aau-giraf/web-api#40]
**Is your feature request related to a problem? Please describe.**
The integration tests are not part of the CI in github actions

**Describe the solution you'd like**
The integration tests are part of the CI in github actions

**Additional context**
The work to add the integraiton tests to the CI in github actions has begun in the branch named "IntegrationTests". There is still missing functionality in the "build_run_it.sh" script created in the branch. The missing functionality is to:

- Build a local database in the github actions before running the IntegrationTests. This should be done according to the README.MD in the web-api repository.

Secondly it could be nice to refactor the filestructure of the scripts associated to the Integration Tests

- The scripts associated to this functionality should be moved from web-api/scripts to web-api/GirafIntegrationTest/scripts (note this should not change the functionality, only act as a better filestructure)

**Comment by Lortemanden** [comment]
Has this been fixed by removing azure pipeline?

**Comment by mathiasandresen** [comment]
Now relevant for GH Actions
