### ISSUE TITLE
Don´t know what HugeBase64Images.cs is used for

### ISSUE THREAD

**Issue by joandrsn** [aau-giraf/web-api#46]
I don't understand what it's there for anymore. As I see it, it has no references, and simply contains 66K characters.

It could possibly be one large image or many small images.

It's located in [HugeBase64Images.cs](https://github.com/aau-giraf/web-api/blob/master/GirafRest/Data/HugeBase64Images.cs) (`GirafRest/Data/HugeBase64Images.cs`).

To quote the code:
```
/*
 * Beware ye who enters.
 *
 * Here be very long lines.
 */
```

**Comment by Lortemanden** [comment]
Figure out what HugeBase64Images.cs is used for and document it in the readme. If it is not used remove it
