### ISSUE TITLE
As a developer, I would like the table `Pictograms` to not include `ImageHash`.

### ISSUE THREAD

**Issue by Badgie** [aau-giraf/web-api#47]
**Is your feature request related to a problem?**
The `Pictogram` table in the database has an attribute `ImageHash` that is unused in the code (sans assignments in on the object). It is also merely the same hard coded string "Secure Hash" on almost every row.

**Describe the solution you'd like**
I would like for the table to be altered to remove the column.

**Describe alternatives you've considered**
Ignoring the problem, but it can cause confusion for the developer.

**Additional context**
Sample data as seen from MySQL. Please note that "Secure Hash" is the literal string `Secure Hash` and not a placeholder.
```
mysql> SELECT * FROM Pictograms LIMIT 5;
+----+-------------+----------------------------+-------+---------+-------------+
| id | AccessLevel | LastEdit                   | Sound | Title   | ImageHash   |
+----+-------------+----------------------------+-------+---------+-------------+
|  1 |           1 | 2017-05-26 14:53:00.660175 | NULL  | Epik    | 791559      |
|  2 |           1 | 2014-05-14 06:20:18.000000 | NULL  | alfabet | Secure Hash |
|  3 |           1 | 2014-05-14 06:20:18.000000 | NULL  | alle    | Secure Hash |
|  4 |           1 | 2014-05-14 06:20:18.000000 | NULL  | alting  | Secure Hash |
|  5 |           1 | 2014-05-14 06:20:19.000000 | NULL  | antal   | Secure Hash |
+----+-------------+----------------------------+-------+---------+-------------+
``` 

Additionally, when a new pictogram is saved to the database, the hash is simply computed using the built-in system method [GetHashCode()](https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=netframework-4.8). This gets the hash of the object in memory on the  `web-api`. It makes NO sense to save this to the database.

**Comment by Lortemanden** [comment]
I don't get what the problem is and what you would like to be done to fix this problem?

**Comment by soenderby** [comment]
This is made irrelevant by #159
