### ISSUE TITLE
There is no sanity checks in PictogramController.cs

### ISSUE THREAD

**Issue by rasmus91** [aau-giraf/web-api#48]
Currently there are no sanity checks in the PictogramController, which means an exception will be thrown in the controller, and nothing returned to the client, in case of a pictogram not existing. Everytime a pictogram is read:

1. check if the file exists
2. read the file contents (in a try catch)

then return the data to the client.

**Comment by Lortemanden** [comment]
Group 7 has worked with this in sprint 1.
They have fixed the issue, but is waiting for #52 to push.
Group 7 would like to work with this in sprint 2.
