### ISSUE TITLE
Remove hardcoded values from Controller

### ISSUE THREAD

**Issue by joandrsn** [aau-giraf/web-api#49]
In some of the controllers, there are some hardcoded strings.
In the `PictogramController` many of the pictures are referenced by a ` + ".png"` which indicates that the server only accepts png images. But I don't see any sanity checks on the actual filetype.
So the file might actually be a jpeg or maybe an .exe, but the file is simply written to the disk.

First should you maybe just do some sanity checks. 

On files then instead of linking files from the primary key as seen here:
https://github.com/aau-giraf/web-api/blob/a7ca02c3e5f3fdce1d6645d5f9549ac659977d24/GirafRest/Controllers/PictogramController.cs#L281
One could instead use a `Path` variable on `Pictogram` class to reference the file uploaded.

**Comment by Lortemanden** [comment]
Is this issue not the same as issue #48

**Comment by joandrsn** [comment]
No it's not.
This issue is concerned with that one could assume that images always are saved as `.png`. But if I were to upload a `.jpg` image, the file is saved as `123.png` eventhough it's a `jpg`-file.

**Comment by Mustafa-ALD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue 49](https://trello.com/c/P7uddhnu/30-issue-49)

**Comment by Emil7370** [comment]
Pictures uploaded are decoded into a single frame image and then reencoded as PNG images. So the correct file extension is always .png. It is possible to encode it as something else but the current soulution works fine and allows for upload of many file types including the most common such as png, jpg and gif.

**Comment by Emil7370** [comment]
Pictures uploaded are decoded into a single frame image and then reencoded as PNG images. So the correct file extension is always .png. It is possible to encode it as something else but the current solution works fine and allows for upload of many file types including the most common such as png, jpg and gif.

The images are reencoded on line 88 in \lib\blocs\upload_from_gallery_bloc.dart
`return encodePng(copyResize(decodeImage(file.readAsBytesSync())`
