### ISSUE TITLE
Illogical endpoints

### ISSUE THREAD

**Issue by boginw** [aau-giraf/web-api#5]
**Describe the bug**
Looking at the endpoints available on [Swagger](http://web.giraf.cs.aau.dk:5100/swagger/) under `Account`, all endpoints start with `/v1/Account/`, except those regarding passwords, which start with `/v1/User`. This looks very weird and should be made to look like the rest.

**To Reproduce**
1. Visit [http://web.giraf.cs.aau.dk:5100/swagger/](http://web.giraf.cs.aau.dk:5100/swagger/)
2. Expand Account
3. Observer endpoints

**Expected behavior**
All endpoints under `Account` should start with `/v1/Account`.

**Actual behavior**
Some endpoints start with `/v1/User`

**Screenshots**
![Screenshot from 2019-03-10 12-06-29](https://user-images.githubusercontent.com/5813142/54084119-fd5f1600-432c-11e9-91f5-cd071fb8f25c.png)

**Environment (please complete the following information):**
- Any
- No
- N/A
- N/A

**Additional context**
This can produce artifacts down the line which can inconvenience future developers.

**Comment by Lortemanden** [comment]
Does this bug still happen? The link does not work so is unsure.

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 5](https://trello.com/c/s0RdvLrB/45-issue-5)

**Comment by dkalaxdk** [comment]
Closed in pull request #172
