### ISSUE TITLE
There is no fallback image

### ISSUE THREAD

**Issue by rasmus91** [aau-giraf/web-api#50]
Currently the pictogramcontroller does not return data in case the requested image does not exist. Instead, there should be a fallback image from which it is immediatly clear that the requested pictogram does not exist, or wasn't found.

1. Create an image (preferrable in GIMP/Inkscape, some other easily editable format)
2. Implement reading and returning the fallback image on the server side.

This issue should be resolved after/depends on: #48

**Comment by Lortemanden** [comment]
The fallback image can be found here or in the design guide
![FallBackAsset](https://user-images.githubusercontent.com/55434783/77319795-bbbec480-6d0f-11ea-9f28-589f39291467.png)

**Comment by Lortemanden** [comment]
This hash been fixed by #48

**Comment by joandrsn** [comment]
@Lortemanden why do you believe that it has been closed by that issue?
There still is not a fallback image. #48 only made some more checks on if the file actually exists.
I would argue that this issue has to be reopened.
