### ISSUE TITLE
The API uses a outdated version of .NET Core

### ISSUE THREAD

**Issue by Badgie** [aau-giraf/web-api#52]
The API uses .NET Core 2.2, which reached EOL in December 2019. It should be updated to use 3.1 which has LTS until December 2022. See [.NET Core Support Policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

**Comment by TobiasNielsen** [comment]
Remember to update the readme file, such it state the version used.

**Comment by Lortemanden** [comment]
Group 7 has worked with this in sprint 1.
The unit test needed to be updated else the issue is done 
Group 7 would like to work with this in sprint 2.
