### ISSUE TITLE
Convert database tables to use either singular or plural forms

### ISSUE THREAD

**Issue by joandrsn** [aau-giraf/web-api#53]
According to the Database System Concepts book p. 345 under 7.9.2 *Naming of Attributes and Relationships*, names should either be in plural or singular form.

`Setting` in the current database is not plural. Screenshot from the command `show tables;`-command executed inside the database:
![image](https://user-images.githubusercontent.com/5766695/75350712-40502b80-58a7-11ea-80a6-7aae6bb5ebca.png)

Without understanding the entirety of the Entity Framework, it could be as simple as just renaming the variables in this file:
https://github.com/aau-giraf/web-api/blob/a7ca02c3e5f3fdce1d6645d5f9549ac659977d24/GirafRest/Data/GirafDbContext.cs#L20-L34

eg. rename from `Departments` to `Department`

**Comment by Lortemanden** [comment]
hte file GirafDbContext.cs does not contain all the tables shown in the picture above? Are they located in another file together withe the setting table? Also would it not be easier to rename setting to settings?

**Comment by joandrsn** [comment]
Are you talking about the tables `AspNetUsers` and such? I don't know where they come from, but that would be a possible thing to explore from the assignee of this issue.

It could be easier to rename from `Setting` to `Settings`. As long as they are consistent.
