### ISSUE TITLE
DbInitializer.cs has all sample data hardcoded

### ISSUE THREAD

**Issue by rasmus91** [aau-giraf/web-api#54]
Currently DbInitializer.cs has all sample data hardcoded. this includes pictogram info, users and weekdays. Instead a sampledata.json file should be created containing all this information, and then methods in DbInitializer.cs should be made to read that data and update it. 

There are at least 2 benefits to this: The class file will then contain code only, NOT data. rebuilding the entire project is not necessary to make changes to the sample data.

1. Create a json file, and add sample data
2. Let DbInitializer.cs methods read data from the json file and seed the DB with that.

**Comment by mathiasandresen** [comment]
Is in progress: https://github.com/aau-giraf/web-api/tree/fixes_54

**Comment by Lortemanden** [comment]
Group 12 has worked with this in sprint 1.
The pull request was reverted. The issue is done but needs to be pushed with another pull request.
Group 12 would like to work with this in sprint 2.
