### ISSUE TITLE
Considering updating frameworks in web-api

### ISSUE THREAD

**Issue by jenspetur94** [aau-giraf/web-api#6]
The web API is currently running outdated versions of ASP.NET core and Entity framework core.
The backend skill group should consider if it would be worth it to update the frameworks.

There are possibly other frameworks that are out of date. I have not looked further into it.

**Comment by sipman** [comment]
@jenspetur94 Should we consider this as a highpriority ?

**Comment by thomaslhansen** [comment]
Framework was updated to dotnet 2.2 and was merged into develop with PR #13 and is no longer relevant.
