### ISSUE TITLE
Integration tests needs fixing, since most are either skipped or failed

### ISSUE THREAD

**Issue by Rsvend17** [aau-giraf/web-api#67]
**Describe the bug**
Most of the Wep-API integration tests fails. Suspected to be, because of new versions of different packages. 

**To Reproduce**
1. Open Wep-api project in a pycharm.
2. Install required packages ( Make sure that the package 'integrate' has the version 1.2.1, else it will not be able to run at all, because of changes to the new version of that package)
3. run file "test.py" from folder "GirafIntegrationTest.tests". 
4. see the results of tests

**Expected behavior**
All tests should pass. 

**Actual behavior**
Ran 146 tests, 42 succeeded, 48 failed (0 expected), 56 skipped

**Screenshots**
![image](https://user-images.githubusercontent.com/34129384/76859939-7e16f300-685a-11ea-9e8e-a790472587d5.png)

**Environment (please complete the following information):**
- Local database setup
- Run wep-API locally

**Additional context**

**Comment by Lortemanden** [comment]
Det tests works if the guide in the README is followed
