### ISSUE TITLE
Only citizens should have settings

### ISSUE THREAD

**Issue by TobiasNielsen** [aau-giraf/web-api#70]
**Describe the bug**
Related to https://github.com/aau-giraf/api_client/issues/23

**To Reproduce**
register a new user

**Expected behavior**
A setting tuple should only be created if user is citizen.

**Actual behavior**
When creating a new user, a settings tuple is created in settings table.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by Laexander** [comment]
Should be done, but can't ensure that tests work due to #67. 
Once fixed tests should be revisited to ensure they work.
