### ISSUE TITLE
[IntegrationTest] clean up code and use built-in testing module

### ISSUE THREAD

**Issue by Badgie** [aau-giraf/web-api#73]
The integration tests are quite messy. It does not follow the proper Python coding style - and where it does, there are better, more readable ways -, it uses several different naming conventions, and it even has semicolons. This should be refactored.

The module used for testing, [integrate](https://pypi.org/project/integrate/), is rather obscure. It does not add much functionality over the built-in module, and it tries to re-implement many of the built-in functions, rather than use them. Additionally, exception stacktraces are contained only within the integrate module when your tests fail - you do not get any useful information as to the origin of the exception. Use the built-in module [unittests](https://docs.python.org/3/library/unittest.html) instead.

**Comment by mathiasandresen** [comment]
Good idea! Remember to update the wiki also
