### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by Seraph2** [aau-giraf/web-api#74]
The project should be run through a software that can check the project's code coverage, in order to figure out which parts of the codebase is covered by tests.

It seems as Coverlet should be added in order to retrieve the coverage of the project. A guide can be found [here](https://codeburst.io/code-coverage-in-net-core-projects-c3d6536fd7d7).

The data retrieved from Coverlet should then be uploaded to a service like [Codecov](http://codecov.com/) for visual display.

**Comment by Lortemanden** [comment]
This is related to issue aau-giraf/weekplanner#326
