### ISSUE TITLE
Remove redundant endpoint

### ISSUE THREAD

**Issue by Badgie** [aau-giraf/web-api#91]
The endpoint `/v1/Department/{departmentId}/user/{userId}` adds a user *that does not have a department* to department with id `departmentId`. However, it is not possible to register a user without specifying a department, and additionally, when you delete a department, any user belonging to that department is also deleted. As such, it is not possible to have a user that does not belong to a department. The aforementioned endpoint should be removed, or a user should be able to exist without a department.

**Comment by Lortemanden** [comment]
The endpoint should be removed since a user is not able to exist without a department

**Comment by JeppeKLau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 91](https://trello.com/c/pMGtJpnx/56-issue-91)
