### ISSUE TITLE
As a developer, I expect the repository to have consistent indentation and line endings

### ISSUE THREAD

**Issue by Seraph2** [aau-giraf/web-api#92]
**Is your feature request related to a problem? Please describe.**
Indentation is of code and line endings are different in many places and should be formatted consistently.
Creating my own little PowerShell script to analyze the source, I get the following result:
![image](https://user-images.githubusercontent.com/5766695/80200941-a943ed80-8623-11ea-8012-d7b972badf8c.png)

**Describe the solution you'd like**
I'd like to see the files using a consistent formatting, and this should be done automatically, perhaps using a tool.

**Additional context**
I would suggest using a config for [EditorConfig](https://editorconfig.org/). This would make it easy for developers to align with a standard which they don't have to think about.

Additionally, if the lineendings were set specifically, we would reduce the risk of having PRs with lineending changes (which has happened multiple times).

**Comment by Andreas2762** [comment]
If both indentation and line-endings should be consistent, what should be the default then? Indentation could be either tabs or spaces, and if the latter, should it be 2 or 4 spaces? Line-endings could be LF or CRLF?
